---

     - name: Copy properties files to Jboss server Configuration directory
       copy: src=roles/centos-jboss7-deployment/files/standalone.xml dest=/home/lms/jboss-as-7.1.1.Final/standalone/configuration

     - name: Replace standalone.conf file in "bin"
       template: src=roles/centos-jboss7-deployment/files/standalone.conf dest=/home/lms/jboss-as-7.1.1.Final/bin/
 
     - name: Edit PMS, EMS Datasource Information
       replace: dest=/home/lms/jboss-as-7.1.1.Final/standalone/configuration/standalone.xml regexp={{ item.regexp }} replace={{ item.replace }}
       with_items:
           - { regexp: 'DataSourcePMS_URL', replace: "{{pmsDatabaseHost}}/{{pmsDatabaseName}}" }
           - { regexp: 'PMSDB_Username', replace: "{{pmsDatabaseUsername}}" }
           - { regexp: 'PMSDB_Password', replace: "{{pmsDatabasePassword}}" }
           - { regexp: 'DataSourceSLE_URL', replace: "{{sleDatabaseHost}}/{{sleDatabaseName}}" }
           - { regexp: 'SLEDB_Username', replace: "{{sleDatabaseUsername}}" }
           - { regexp: 'SLEDB_Password', replace: "{{sleDatabasePassword}}" }

     - name: Copy standalone configuration file
       copy: src=roles/centos-jboss7-deployment/files/standalone.conf dest=/home/lms/jboss-as-7.1.1.Final/bin

     - name: Copy Skilrock modules to original Jboss Directory
       copy: src=roles/centos-jboss7-deployment/files/skilrock dest=/home/lms/jboss-as-7.1.1.Final/modules/com

     - name: Copy mysql modules to original Jboss Directory
       copy: src=roles/centos-jboss7-deployment/files/mysql dest=/home/lms/jboss-as-7.1.1.Final/modules/com

     - name: Copy MTN Directory Skilrock/LMS/DGE           
       copy: src=roles/centos-jboss7-deployment/files/MTN dest=/home/lms/jboss-as-7.1.1.Final/modules/com/skilrock/configuration/main/LMS/DGE
       when: client == "lagos"

     - name: Copy MTN Properties in Skilrock/LMS/DGE
       copy: src=roles/centos-jboss7-deployment/files/MTN.properties dest=/home/lms/jboss-as-7.1.1.Final/modules/com/skilrock/configuration/main/LMS/DGE
       when: client == "lagos"

     - name: Copy MTN_TEST.properties in Skilrock/LMS/DGE
       copy: src=roles/centos-jboss7-deployment/files/MTN_TEST.properties dest=/home/lms/jboss-as-7.1.1.Final/modules/com/skilrock/configuration/main/LMS/DGE
       when: client == "lagos"

     - name: Edit MTN_TEST.properties
       replace: dest=/home/lms/jboss-as-7.1.1.Final/modules/com/skilrock/configuration/main/LMS/DGE/MTN_TEST.properties  regexp='mtn.wsdlPath*' replace="mtn.wsdlPath:=file:///home/lms/jboss-as-7.1.1.Final/modules/com/skilrock/LMS/DGE/"
       when: client == "lagos"

     - name: Enter Database name in DGE Properties file
       lineinfile: dest=/home/lms/jboss-as-7.1.1.Final/modules/com/skilrock/configuration/main/LMS/DGE/DG.properties regexp={{ item.regexp }} line={{ item.line }}
       with_items:
           - { regexp: 'databaseName=*', line: 'databaseName={{dgeDatabaseName}}' }
           - { regexp: 'userName=*', line: 'userName={{dgeDatabaseUsername}}' }
           - { regexp: 'hostAddress=*', line: 'hostAddress={{dgeDatabaseHost}}' }
           - { regexp: 'password=*', line: 'password={{dgeDatabasePassword}}' }

     - name: Enter Database Credentials in DGW Properties file
       lineinfile: dest=/home/lms/jboss-as-7.1.1.Final/modules/com/skilrock/configuration/main/LMS/DGW/DGW.properties regexp={{ item.regexp }} line={{ item.line }}
       with_items:
           - { regexp: 'databaseName=*', line: 'databaseName={{dgwDatabaseName}}' }
           - { regexp: 'userName=*', line: 'userName={{dgwDatabaseUsername}}' }
           - { regexp: 'hostAddress=*', line: 'hostAddress={{dgwDatabaseHost}}' }
           - { regexp: 'password=*', line: 'password={{dgwDatabasePassword}}' }
           - { regexp: 'webUrl=*', line: 'hosturl={{drawmachineurl}}' }
           - { regexp: 'ip=*', line: 'hostip={{drawmachineip}}' }
           


