---
 - name: install epel-release
   yum: name=epel-release state=present
 - name: Install pip
   yum: name=python-pip state=present
 - name: upgarde pip
   command: pip install --upgrade pip
 - name: install Mysql python client
   yum: name=MySQL-python state=present

 - name: Create a new database
   mysql_db:   name="{{ item }}" state=present login_user={{rmsDatabaseUsername}} login_password={{rmsDatabasePassword}} login_host={{rmsDatabaseHost}}
   with_items: [ "{{ rmsDatabaseName}}","{{pmsDatabaseName}}","{{dgeDatabaseName}}","{{dgwDatabaseName}}","{{sleDatabaseName}}"]


