---
- name: copy start up Script 
  copy: src=roles/Jboss7Service/files/jboss7 dest=/etc/init.d/ owner=root group=root mode=755 
- name: create link in rc3.d
  file:
    src: /etc/init.d/jboss7
    dest: /etc/rc3.d/S99jboss7
    state: link
- name: copy unit file
  copy:  src=roles/Jboss7Service/files/jboss7.service dest=/etc/systemd/system/ owner=root group=root 
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
- name: Reload System daemon
  command: systemctl daemon-reload
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" 
- name: Start JBoss7 Service
  service: name=jboss7  state=started
- name: Enable JBoss to be started at boot
  service: name=jboss7  enabled=yes
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"


