---
- name: Update DGE War Name
  replace:
    dest: /home/lms/jboss-as-7.1.1.Final/modules/com/skilrock/configuration/main/LMS/{{item}}/{{item}}.properties
    regexp: "^JBOSS_AS_DEPLOYMENT=*.*"
    replace: "JBOSS_AS_DEPLOYMENT={{FileName[0:-4]}}.war"
  with_items:
     - DGW
     - PMS
  when:  ArtifactId == "DGE"
- name: stop jboss4 service
  command: "service jboss4 stop"
  when: ArtifactId == "rms"
- name: Remove old war
  shell: "rm -rf /home/lms/jboss-4.2.3.GA/server/default/deploy/{{ArtifactId}}*" 
  when:  ArtifactId == "rms"
- name: Remove work/tmp/data folder from jboss-4
  file: path=/home/lms/jboss-4.2.3.GA/server/default/{{ item }} state=absent
  with_items:
      - "data"
      - "tmp"
      - "work"
- name: Add new war
  copy: src="/home/lms/Deploy/{{FileName[0:-4]}}/app/{{FileName[0:-4]}}.war" dest="/home/lms/jboss-4.2.3.GA/server/default/deploy/" remote_src=true
  when:  ArtifactId == "rms"
- name: start jboss4 server
  command: "service jboss4 start"
  when: ArtifactId == "rms"
- name: Stop Jboss 7
  command: "service jboss7 stop"
  when: ArtifactId == "DGE"  or ArtifactId == "sportslottery" or ArtifactId == "PMS" or ArtifactId == "DrawGameWeb" or ArtifactId == "SportsLotteryResult"
- name: Remove tmp/data folder from jboss-7
  file: path=/home/lms/jboss-as-7.1.1.Final/standalone/{{ item }} state=absent
  with_items:
      - "data"
      - "tmp"
- name: perform hot deploy
  shell: "rm -rf /home/lms/jboss-as-7.1.1.Final/standalone/deployments/{{ArtifactId}}*.*"
  when: ArtifactId == "DGE"  or ArtifactId == "sportslottery" or ArtifactId == "PMS" or ArtifactId == "DrawGameWeb" or ArtifactId == "SportsLotteryResult"
- name: Start jboss 7
  command: "service jboss7 start"
  when: ArtifactId == "DGE"  or ArtifactId == "sportslottery" or ArtifactId == "PMS" or ArtifactId == "DrawGameWeb" or ArtifactId == "SportsLotteryResult"
- name: Add new war
  copy: src="/home/lms/Deploy/{{FileName[0:-4]}}/app/{{FileName[0:-4]}}.war" dest="/home/lms/jboss-as-7.1.1.Final/standalone/deployments/" remote_src=true
  when: ArtifactId == "DGE"  or ArtifactId == "sportslottery" or ArtifactId == "PMS" or ArtifactId == "DrawGameWeb" or ArtifactId == "SportsLotteryResult"
- name: Stop Wildfly10 Instance
  command: "/etc/init.d/wildfly10 stop"
  when: ArtifactId == "ims"
- name: Remove tmp/data folder from wildfly10
  file: path=/home/lms/wildfly-10.1.0.Final/standalone/{{ item }} state=absent
  with_items:
      - "data"
      - "tmp"
- name: Perform hot Deployment on wildfly server
  shell: "rm -rf /home/lms/wildfly-10.1.0.Final/standalone/deployments/{{ArtifactId}}*.*"
  when: ArtifactId == "ims"
- name: Start wildfly server
  command: "/etc/init.d/wildfly10 start"
  when: ArtifactId == "ims"
- name: Add New war file
  copy: src="/home/lms/Deploy/{{FileName[0:-4]}}/app/{{FileName[0:-4]}}.war" dest="/home/lms/wildfly-10.1.0.Final/standalone/deployments/" remote_src=true
  when: ArtifactId == "ims"
- name: Delete old packages 
  shell: "rm -rf /home/lms/Deploy/{{ArtifactId}}*.*"
